name: connectinno_case
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  flutter_hooks: ^0.21.2
  gap: ^3.0.1
  flutter_bloc: ^8.1.3
  auto_route: ^7.8.4
  flutter_secure_storage: ^9.2.4
  supabase_flutter: ^2.10.0
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
